[default]
SECRET_KEY = "your-secret-key"
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://<sql_username>:<sql_password>@<mysql_address>:<mysql_port>/<sql_name>"
SQLALCHEMY_TRACK_MODIFICATIONS = false

MAIL_SERVER = "smtp.example.com"
MAIL_PORT = 587
MAIL_USE_TLS = true
MAIL_USERNAME = "your-email@example.com"
MAIL_PASSWORD = "your-email-password"

[admin]
username = "admin"    #http basic auth username
password = "19260817" #http basic auth password

[captcha]
length = 5  # 验证码长度
digits = false  # 是否仅包含数字
expire = 300  # 验证码有效期（秒）
secret_key = "LONG-KEY"  # 验证码加密密钥
exclude_visually_similar = true  # 是否排除视觉上相似的字符
background_color = [0, 0, 0]  # 验证码背景颜色（RGB）
log = false  # 是否记录验证码日志